export const API_ACTIONS = [
  "session.bootstrap",
  "household.create",
  "household.list",
  "household.invite.create",
  "household.invite.accept",
  "household.member.list",
  "household.member.remove",
  "household.admin.transfer",
  "household.settings.update",
  "household.dissolve",
  "category.list",
  "category.save",
  "category.reorder",
  "location.list",
  "location.save",
  "item.create",
  "item.update",
  "item.list",
  "item.detail",
  "item.quantity.change",
  "item.process",
  "item.delete",
  "item.restore",
  "item.bulkMoveCategory",
  "catalog.lookup",
  "catalog.findMergeCandidate",
  "reminder.list",
  "reminder.markRead",
  "media.tempUrl",
  "account.export",
  "account.delete",
] as const;

export type ApiAction = (typeof API_ACTIONS)[number];
